Extended address endpoint
adityabisoi/REST-fetch pull request #106
Opened 2021-04-22 14:19 UTC by Samridhi-98

# Related Issue

-   closes #102 

# Proposed Changes

- [x]  Added route with query param /address?city=xyz

- [x]  Added route with query param /address?state=xyz

- [x] Added route with query param /address?country=xyz

# Checklist

-   [x] Tests
-   [x] Translations

2021-04-22 14:19 UTC, Samridhi-98 commented
@ShauryaAg  @paramsiddharth  Please review my PR.

2021-04-22 14:42 UTC, ShauryaAg requested changes

2021-04-22 14:42 UTC, ShauryaAg commented on data/addressdata.json
> +            "country": "india",
Please don't convert all of this to lower case. Use [`.toLowerCase()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLowerCase) function while checking the condition.

2021-04-22 14:42 UTC, ShauryaAg commented on src/api/routes/address.ts
> +        for (let i = 0; i < data.data.length; i++) {
Don't use a for loop to iterate over all of them. Use [`.filter()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) method.

2021-04-22 15:31 UTC, Samridhi-98 commented
@ShauryaAg  Done! please review

2021-04-22 16:12 UTC, ShauryaAg requested changes
We can also chain multiple `.filter()` methods to query based on multiple things at once.

Something like
```js
result = data.data
          .filter(condition1) // check for city
          .filter(condition2) // check for state
          .filter(condition3) // check for country
```

So that user may query like `/address?state=xyz&city=abc`

Please see if you can implement this, otherwise feel free contact us on the discord channel.

2021-04-22 18:21 UTC, Samridhi-98 commented
@ShauryaAg  Done, updated filter chaining as you suggested on discord please review.

2021-04-22 21:00 UTC, ShauryaAg requested changes

2021-04-22 21:00 UTC, ShauryaAg commented on src/api/routes/address.ts
> +                let result = data.data
change `let` to `const`

2021-04-22 21:03 UTC, ShauryaAg requested changes

2021-04-22 21:03 UTC, ShauryaAg commented on src/api/routes/address.ts
> +                    res.status(404).json({ message: "No data found" });
`res.status` should be `204` when no records are found.

2021-04-23 05:55 UTC, Samridhi-98 commented
@ShauryaAg  Done!

2021-04-23 05:56 UTC, paramsiddharth approved these changes

2021-04-24 03:17 UTC, paramsiddharth commented
@Samridhi-98 Thank you!

2021-04-24 03:17 UTC, merged