Improvised animals route
adityabisoi/REST-fetch pull request #133
Opened 2021-05-04 07:22 UTC by ritik307

# Related Issue

-   closes #132 

# Proposed Changes

- [x] Add  json file with appropiate data in `data/animals/amphibianData.json`
- [x] Add endpoint `animals/amphibians` in `animals.ts`
- [x] Add enpoint `animals/amphibians/:type` in `animals.ts`

# Checklist

-   [x] Tests
-   [x] Translations
-   [x] Documentation

2021-05-04 07:22 UTC, ritik307 commented
@paramsiddharth @ShauryaAg Plz review

2021-05-04 12:10 UTC, paramsiddharth commented
@ritik307 Make it as follows:
1. GETting /animals returns all animals.
2. GETting /animals/amphibians returns amphibians.

As I can see, currently we only have amphibians (correct me if I am wrong). Once other categories are added, they should also be returned along with amphibians on GETting the /animals route.

2021-05-04 12:30 UTC, ShauryaAg requested changes

2021-05-04 12:30 UTC, ShauryaAg commented on data/animals/amphibiandata.json
> +    "data": [{
Put `{` in the next line.

2021-05-04 16:06 UTC, ritik307 commented
@ShauryaAg @paramsiddharth Plz review the changes.

2021-05-05 18:59 UTC, ShauryaAg approved these changes

2021-05-06 07:08 UTC, paramsiddharth approved these changes

2021-05-06 07:08 UTC, paramsiddharth commented
@ritik307 Thank you!

2021-05-06 07:08 UTC, merged