Extended animals route
adityabisoi/REST-fetch pull request #138
Opened 2021-05-07 12:06 UTC by ritik307

# Related Issue

-   closes #136 

# Proposed Changes
- [x] add following categories- `bird`, `reptile`, `fish`.
- [x] add endpoint `animals/:category?type=abc`

# Checklist

-   [x] Tests
-   [x] Translations
-   [x] Documentation

2021-05-07 12:06 UTC, ritik307 commented
@paramsiddharth @ShauryaAg Plz review.

2021-05-07 18:28 UTC, ShauryaAg requested changes

2021-05-07 18:28 UTC, ShauryaAg commented on src/api/routes/animals.ts
> +    let result = data.data.filter((animal: any) => animal.category === category)[0];
Use `.find` method instead of `.filter`

2021-05-07 18:28 UTC, ShauryaAg commented on src/api/routes/animals.ts
> +            if (Object.keys(req.query).length) {
These if statements can be combined into one.

2021-05-07 18:28 UTC, ShauryaAg commented on src/api/routes/animals.ts
> +                        res.status(204).json({ message: "No data found" });
Use braces for `if/else` statements.

2021-05-07 18:28 UTC, ShauryaAg commented on src/api/routes/animals.ts
> +                res.status(200).json(result);
Add braces.

2021-05-07 18:28 UTC, ShauryaAg commented on src/api/routes/animals.ts
> +            res.status(404).json({ message: "Invalid category" });
Add braces

2021-05-07 18:28 UTC, ShauryaAg commented on src/api/routes/animals.ts
> +
Remove extra line.

2021-05-07 19:05 UTC, ritik307 commented
@ShauryaAg Done! Plz check

2021-05-07 20:32 UTC, ShauryaAg requested changes

2021-05-07 20:32 UTC, ShauryaAg commented on src/api/routes/animals.ts
> +                else {
Move `else` to upper line, like 
```js
if {
...
} else {
...
}
```

2021-05-07 20:32 UTC, ShauryaAg commented on src/api/routes/animals.ts
> +                res.status(404).json({ message: "Invalid category" });
Move `else` to upper line

2021-05-07 20:32 UTC, ShauryaAg commented on src/api/routes/animals.ts
> +        else {
Move `else`

2021-05-07 20:32 UTC, ShauryaAg commented on src/api/routes/animals.ts
> +    console.log(result);
Remove unnecessary console logs.

2021-05-08 10:40 UTC, ShauryaAg approved these changes

2021-05-08 10:41 UTC, merged

2021-05-08 13:17 UTC, ritik307 commented
@ShauryaAg Plz add appropriate tags