Fixed issue #2, Add issue template: bug report
adityabisoi/REST-fetch pull request #25
Opened 2021-03-11 08:00 UTC by rithgan

# Related Issue
issue #2 

# Proposed Changes
Add issue template: bug report

2021-03-11 11:17 UTC, ShauryaAg requested changes
Please add **Logs (if applicable)** too

2021-03-11 11:17 UTC, ShauryaAg commented on .github/ISSUE_TEMPLATE/bug_report.md
> +If applicable, add screenshots/ screen recordings to help explain your problem.
Please remove the space after `/`

2021-03-11 11:17 UTC, ShauryaAg commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**System Information(please complete the following information):**
Please add a space before `(`

2021-03-11 11:47 UTC, rithgan commented
Please review.

Also my discord username is - kiraa#7281

2021-03-11 12:30 UTC, ShauryaAg approved these changes

2021-03-12 09:05 UTC, rithgan commented
@ShauryaAg I am really sorry but I think I accidentally closed this pull request. How can I reopen it?

2021-03-12 09:16 UTC, ShauryaAg commented
@rithgan you also force pushed on your branch, making the previous changes invalid. Please revert the last commit, and then I can reopen the PR for you again

2021-03-12 09:18 UTC, rithgan commented
> @rithgan you also force pushed on your branch, making the previous changes invalid. Please revert the last commit, and then I can reopen the PR for you again

Thanks but I think I got it. I had rebased origin/main to upstream/main due to which I went to the last commit on the original branch. All I had to was make the commit again on the forked branch and reopen the pull request.

2021-03-12 17:42 UTC, adityabisoi commented
@rithgan Also remember to use auto issue closing writing syntax, such as closes #2 https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

2021-03-12 17:42 UTC, merged