added POST method to /users endpoint
adityabisoi/REST-fetch pull request #42
Opened 2021-03-15 07:25 UTC by EANimesha

**request :** 
 endpoint : /users (POST)
 payload: 
  

>  Content-type- json
>   {
>     "first_name":"Name1",
>     "last_name":"Name2",
>     "email":"n@gmail.com"
>  }

**response:**

> {
>     "timestamp": 1615792926283,
>     "data": {
>         "_id": "604f0b1e4e98a0516137b359",
>         "first_name": "Name1",
>         "last_name": "Name2",
>         "email": "n@gmail.com"
>     }
> }

2021-03-18 09:22 UTC, adityabisoi commented
@EANimesha We do not need to include the "data"  and "_id" fields. The timestamp should be the last field in proper format, `MM-DD-YY-HH-MM`
```
"first_name":
"last_name":
"email":
"timestamp":
```

2021-03-18 14:16 UTC, EANimesha commented
Updated. now response is 
```
{
    "first_name": "Name1",
    "last_name": "Name2",
    "email": "n@gmail.com",
    "timestamp": "2021-03-18 19-44"
}
```

2021-03-20 13:17 UTC, adityabisoi commented
This PR still needs some corrections. Firstly, there is no need to create a mongodb instance from the accepted data. Also,
the user might send data with fields other than `first_name`, `last_name`, and `email`. The issue asks to send `any` data that is received, back with a timestamp.

2021-03-21 12:21 UTC, ShauryaAg requested changes

2021-03-21 12:21 UTC, ShauryaAg commented on src/api/routes/users.ts
> +var dateFormat = require('dateformat');
Change this to `import` statement

2021-03-21 16:23 UTC, ShauryaAg requested changes

2021-03-21 16:23 UTC, ShauryaAg commented on src/api/routes/users.ts
> -import mongoose from 'mongoose'
Why was this line removed?

2021-03-23 09:05 UTC, ShauryaAg approved these changes

2021-03-23 09:06 UTC, ShauryaAg commented
@EANimesha Can you please resolve the merge conflicts?

2021-03-24 11:51 UTC, EANimesha commented
> @EANimesha Can you please resolve the merge conflicts?

@ShauryaAg resolved conflicts

2021-03-27 05:33 UTC, paramsiddharth approved these changes

2021-03-27 07:05 UTC, paramsiddharth commented
@EANimesha The POSTed user object should properly fit into the user model and should be checked for the presence and validity of all fields a user must have. Please update the logic to do that.

2021-03-27 17:22 UTC, paramsiddharth commented
@EANimesha It would be appropriate to validate the schema before successfully sending back the response with status 200. Extra/Missing parameters should be checked for and errors should be shown accordingly.

2021-04-01 09:33 UTC, ShauryaAg requested changes

2021-04-01 09:33 UTC, ShauryaAg commented on src/api/routes/users.ts
> +    res.status(200).json(userData)
@EANimesha Can you please update the PR to verify the data sent with the user schema. `req.body` should not contain any field that is not used by the `user` model.

2021-04-09 16:32 UTC, adityabisoi commented
@EANimesha This issue has been laying around for a while now. Please make the commented changes and I shall merge it.

2021-04-09 17:07 UTC, EANimesha commented
Sorry that branch of my forked repo got deleted. I couldn't open it again. I had to open another PR for that

2021-04-11 09:37 UTC, closed without merging