patch method added
adityabisoi/REST-fetch pull request #51
Opened 2021-03-20 06:51 UTC by subhangi2731

fixes #40 patch method added

2021-03-20 17:59 UTC, ShauryaAg requested changes
Don't commit your `package-lock.json`

2021-03-20 17:59 UTC, ShauryaAg commented on package.json
> +    "mongoose": "^5.12.1",
Why did you change the mongoose version?

2021-03-21 12:50 UTC, adityabisoi commented
Also, the method has hardcoded fields. We must return anything that is received, with a timestamp.

2021-03-21 12:53 UTC, subhangi2731 commented
I will update the pr now @adityabisoi

2021-03-21 12:58 UTC, merged