modified unit tests added
adityabisoi/REST-fetch pull request #52
Opened 2021-03-20 07:29 UTC by subhangi2731

fixes #39 . Modified the code and unit tests added

2021-03-21 12:20 UTC, ShauryaAg requested changes

2021-03-21 12:20 UTC, ShauryaAg commented on package.json
> +    "mongoose": "^5.12.1",
Why is this needed?

2021-03-27 05:47 UTC, paramsiddharth commented
@subhangi2731 Since you have most probably squashed the commit, start afresh from the current main branch of the repository, and while retaining ` _test_/users.test.js`, do an `npm i -D jest supertest`, recommit, and force-push. The current `package-lock.json` has conflicts, and the bump to Mongoose is not needed.

Also, to ensure consistency, try to use TypeScript instead of JavaScript, just like most of the code in the repository.

2021-03-27 05:47 UTC, paramsiddharth requested changes
@subhangi2731 Since you have probably squashed the commits, start afresh from the current main branch of the repository, and while retaining ` _test_/users.test.js`, do an `npm i -D jest supertest`, recommit, and force-push or make a fresh PR from a new branch. The current `package-lock.json` has conflicts, and the bump to Mongoose is not needed.

Also, to ensure consistency, try to use TypeScript instead of JavaScript, just like most of the code in the repository.

2021-04-08 07:16 UTC, closed without merging