added PATCH req in users route
adityabisoi/REST-fetch pull request #73
Opened 2021-04-03 16:28 UTC by ritik307

# Related Issue
- closes #1 

# Proposed Changes
- added `PATCH` route in `users.ts`

# Checklist
- [x] Tests

2021-04-03 16:28 UTC, ritik307 commented
@ShauryaAg @paramsiddharth  plz review my PR.

2021-04-03 19:06 UTC, ShauryaAg requested changes
@ritik307 Please lint the file, according to the rules defined in config files.

You just need to run `npm run lint`

2021-04-03 19:42 UTC, ritik307 commented
@ShauryaAg Done! got no errors in the file in which I made changes.

2021-04-03 20:05 UTC, ShauryaAg requested changes

2021-04-03 20:05 UTC, ShauryaAg commented on src/api/routes/users.ts
> -        // Single user invalid
Why was this line removed?

2021-04-03 20:05 UTC, ShauryaAg commented on src/api/routes/users.ts
> +    // jsonData['timestamp']=dateFormat(new Date(), "yyyy-mm-dd HH-MM")
Remove this unnecessary line.

2021-04-03 20:05 UTC, ShauryaAg commented on src/api/routes/users.ts
> +        const { first_name=user.first_name,last_name=user.last_name,email=user.email }=jsonData;
Put spaces before and after `=` sign

2021-04-03 20:05 UTC, ShauryaAg commented on src/api/routes/users.ts
> +router.patch("/:id", (req: Request, res: Response, next: NextFunction) => {
Change `id` to `userId`

2021-04-03 20:25 UTC, ritik307 commented
@ShauryaAg Done! Plz check

2021-04-03 20:48 UTC, ShauryaAg approved these changes

2021-04-03 20:48 UTC, merged

2021-04-21 10:09 UTC, ritik307 commented
@ShauryaAg @paramsiddharth plz add appropriate GSSOC tag to this isuse.