Vehicle route
adityabisoi/REST-fetch pull request #82
Opened 2021-04-06 18:48 UTC by ritik307

# Related Issue
- closes #79 

# Proposed Changes
- Added `vehicledata.json` in `data` folder
- Added `vehicles.ts` in `route` folder
- Updated `app.ts` with **vehicle** route

# Checklist
- [x] Tests
- [x] Translations

2021-04-06 18:48 UTC, ritik307 commented
@ShauryaAg  @paramsiddharth plz review

2021-04-07 04:41 UTC, ShauryaAg requested changes

2021-04-07 04:41 UTC, ShauryaAg commented on data/vehicledata.json
> +    "name": [
If you'd take a look at the previously added data. The schema is 

```
{
    "data": {
         ...data
    }
}

```

Please follow the same convention.

2021-04-07 04:41 UTC, ShauryaAg commented on data/vehicledata.json
> +}
Also, I was expecting data to be more like:

```
{
   "data": [
    {
      "name": "Swift",
      "manufacturer": "Maruti",
      "type": "hatchback",
      "fuel": "petrol",
      ...
    },
    {
     ...
    }
  ]
}
```

2021-04-07 10:22 UTC, ritik307 commented
@ShauryaAg Done! Plz the changes review

2021-04-07 11:28 UTC, ShauryaAg approved these changes

2021-04-07 15:42 UTC, ritik307 commented
@ShauryaAg  Done!

2021-04-07 15:57 UTC, merged