added breed and picture
adityabisoi/REST-fetch pull request #87
Opened 2021-04-10 19:28 UTC by ritik307

# Related Issue

-   closes #84 

# Proposed Changes

-   added `/animal/type?option=breed`
-   added `/animal/type?option=picture`

# Checklist

-   [x] Tests
-   [x] Translations

2021-04-10 19:28 UTC, ritik307 commented
@ShauryaAg @paramsiddharth  Plz review

2021-04-10 19:54 UTC, ShauryaAg requested changes

2021-04-10 19:54 UTC, ShauryaAg commented on src/api/routes/animals.ts
> +                    break;
Please return `400` if `query.option` does not match `breed` or `picture`

2021-04-10 19:54 UTC, ShauryaAg commented on src/api/routes/vehicles.ts
> +
Please remove this unnecessary new line.

2021-04-11 08:41 UTC, ritik307 commented
@ShauryaAg Done! Plz check

2021-04-11 09:40 UTC, paramsiddharth approved these changes

2021-04-11 21:33 UTC, ShauryaAg approved these changes

2021-04-12 05:05 UTC, merged

2021-04-12 05:05 UTC, paramsiddharth commented
Thank you!