Added draft github actions workflow to check linting
adityabisoi/REST-fetch pull request #94
Opened 2021-04-16 18:10 UTC by AshuKV

# Related Issue

-   closes #72 

# Proposed Changes

-   change 1
-   change 2

# Additional Info

-   any additional information or context

# Checklist

-   [x] Tests
-   [x] Translations
-   [x] Documentation

# Screenshots

|         Original          |         Updated          |
| :-----------------------: | :----------------------: |
| ** original screenshot ** | ** updated screenshot ** |

2021-04-16 20:37 UTC, ShauryaAg requested changes

2021-04-16 20:37 UTC, ShauryaAg commented on .eslintrc.yml
> +env:
We don't need this. We already have a `.eslintrc` config file

2021-04-16 20:37 UTC, ShauryaAg commented on package.json
> +        "eslint": "^7.24.0",
Why were these changes made?

2021-04-16 20:37 UTC, ShauryaAg commented on .github/workflows/linting.yml
> +          files: ./src/**/*.ts
Instead of using this action. We can just simply use `npm run lint`

2021-04-16 20:39 UTC, ShauryaAg commented
You may use [this](https://docs.github.com/en/actions/guides/building-and-testing-nodejs) and [this](https://sviat-kuzhelev.medium.com/progressive-front-end-ci-on-github-actions-817a29938e4f) for reference.

2021-05-02 13:13 UTC, AshuKV reviewed
I have updated the PR. It can be merged now.

2021-05-02 13:38 UTC, ShauryaAg requested changes

2021-05-02 13:38 UTC, ShauryaAg commented on package.json
> +        "eslint-plugin-react": "^7.23.2",
Why is this change needed?

2021-05-16 13:57 UTC, ShauryaAg approved these changes

2021-05-16 13:57 UTC, merged